### ISSUE TITLE
Cannot access containers using `inject`

### ISSUE THREAD

**Issue by ghost** [sindresorhus/unstated-debug#10]
When using this debugger I cannot access any containers which have been `injected` into my provider. ie:
```
const authContainer = new AuthContainer();
...
<Provider inject={[authContainer]}>
  ...
</Provider>
```
Is there any way to attach to these containers to view state?

**Comment by tbiller** [comment]
This is probably due to instantiating your container before importing unstated-debug. Move unstated-debug higher in your import list so that it is around when your containers are constructed.
