### ISSUE TITLE
Precompile to ES5 before release

### ISSUE THREAD

**Issue by nathanmalishev** [sindresorhus/unstated-debug#3]
Would be nice to have the packaged compiled to ES5, so it would work right out of the box with create-react-app, upon building

**Comment by sindresorhus** [comment]
It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

I'm sorry that `create-react-app` is lacking in this aspect, but it's up to them to support the community. Each package should not be required to specially support `create-react-app`. Please do open an issue on `create-react-app` about this pain point.

**Comment by nathanmalishev** [comment]
Thanks for the speedy response @sindresorhus !
