### ISSUE TITLE
Objects are logged as "Added" and "Deleted", even if empty

### ISSUE THREAD

**Issue by fabiospampinato** [sindresorhus/unstated-debug#4]
Whenever I update the state, without adding or removing anything, those sections are still logged to the console:

<img width="256" alt="screen shot 2018-09-16 at 03 51 56" src="https://user-images.githubusercontent.com/1812093/45592067-e209e400-b963-11e8-894f-beaaccd74f88.png">

I see you're checking if there are no additions or deletions:

https://github.com/sindresorhus/unstated-debug/blob/3d6f4b5f1e67b2b71b71f48f3a63c308c4020042/index.js#L44

https://github.com/sindresorhus/unstated-debug/blob/3d6f4b5f1e67b2b71b71f48f3a63c308c4020042/index.js#L52

But these lines don't take into account empty objects.

Would you consider a PR adding support for detecting empty objects?

**Comment by sindresorhus** [comment]
Good catch. Yes, PR welcome :)
