### ISSUE TITLE
SSR support

### ISSUE THREAD

**Issue by romainquellec** [sindresorhus/unstated-debug#6]
If unstated is executed server side, it polute window object and let think we are browser side.

`window.UNSTATED = UNSTATED;`

**Comment by sindresorhus** [comment]
It didn't break anything as it never advertised SSR support. PR welcome to improve SSR support though.

**Comment by kriscarle** [comment]
@romainquellec @sindresorhus the PR above seems to work for me, then I just put this in my header component that is loaded on every page in my app.

```
if (process.env.NODE_ENV !== 'production') {
  require('unstated-debug')
}
```
